name:                 persistencehs
version:              0.1.0.0
visibility:           public
id:                   persistencehs-0.1.0.0-inplace
key:                  persistencehs-0.1.0.0-inplace
maintainer:           unreasonablyeffective42@gmail.com
author:               Jordan Jacobson
abi:                  inplace
exposed:              True
exposed-modules:      MyLib
import-dirs:
    /home/anandamide/haskell/persistence/dist-newstyle/build/x86_64-linux/ghc-9.6.7/persistencehs-0.1.0.0/build

library-dirs:
    /home/anandamide/haskell/persistence/dist-newstyle/build/x86_64-linux/ghc-9.6.7/persistencehs-0.1.0.0/build

library-dirs-static:
    /home/anandamide/haskell/persistence/dist-newstyle/build/x86_64-linux/ghc-9.6.7/persistencehs-0.1.0.0/build

dynamic-library-dirs:
    /home/anandamide/haskell/persistence/dist-newstyle/build/x86_64-linux/ghc-9.6.7/persistencehs-0.1.0.0/build

data-dir:             /home/anandamide/haskell/persistence/.
hs-libraries:         HSpersistencehs-0.1.0.0-inplace
depends:
    base-4.18.3.0 containers-0.6.7
    matrix-0.3.6.4-8d5283d945d11bb5733b856143fc105d63095d0404cb160f6903d45f2053fbb5

haddock-interfaces:
    /home/anandamide/haskell/persistence/dist-newstyle/build/x86_64-linux/ghc-9.6.7/persistencehs-0.1.0.0/doc/html/persistencehs/persistencehs.haddock

haddock-html:
    /home/anandamide/haskell/persistence/dist-newstyle/build/x86_64-linux/ghc-9.6.7/persistencehs-0.1.0.0/doc/html/persistencehs
